# Generated by Django 3.2.5 on 2023-04-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230404_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favs',
        ),
    ]
