# Generated by Django 3.2.5 on 2023-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_User'),
    ]

    operations = [
    ]
